flutter:

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Medium.ttf
        - asset: fonts/Poppins-SemiBold.ttf
        - asset: fonts/Poppins-Bold.ttf

  uses-material-design: true